### ISSUE TITLE
missing LICENSE file

### ISSUE THREAD

**Issue by mrkz** [gweis/isodate#47]
Please provide a proper LICENSE | COPYING | etc file, so it's clear under which license this project is.

(e.g: it mentions it's BSD, but there are more than 1 BSD license: [BSD-2-Clause](https://spdx.org/licenses/BSD-2-Clause.html#licenseText), [BSD-3-Clause](https://spdx.org/licenses/BSD-3-Clause.html#licenseText), [BSD-4-Clause](https://spdx.org/licenses/BSD-4-Clause.html#licenseText), and many more as specified in [SPDX](https://spdx.org/licenses/)).

Adding a proper file, would allow packagers to integrate this project into linux-distros easier, so please do consider adding this and pushing a release with it.

**Comment by hugovk** [comment]
Done in the fork at https://github.com/isodate/isodate/pull/11.

**Comment by gweis** [comment]
dc0d2b81
