### ISSUE TITLE
parse_time exceptions on seconds that are half microsecond to 60 seconds

### ISSUE THREAD

**Issue by huadongliu** [gweis/isodate#53]
https://github.com/gweis/isodate/blob/master/src/isodate/isotime.py#L127

>>> import isodate
>>> from decimal import Decimal
>>> isodate.parse_datetime('2018-09-22T16:14:59.9999994')
datetime.datetime(2018, 9, 22, 16, 14, 59, 999999)
>>> isodate.parse_datetime('2018-09-22T16:14:59.9999995')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nail/home/hliu/isodate/.tox/py36/lib/python3.6/site-packages/isodate/isodatetime.py", line 56, in parse_datetime
    tmptime = parse_time(timestring)
  File "/nail/home/hliu/isodate/.tox/py36/lib/python3.6/site-packages/isodate/isotime.py", line 133, in parse_time
    tzinfo)
ValueError: second must be in 0..59
>>> print(Decimal('59.9999995').quantize(Decimal('.000001')))
60.000000
>>> print(Decimal('59.9999994').quantize(Decimal('.000001')))
59.999999

**Comment by podfran** [comment]
Hi, I'm having the same issue. In C# `DateTime.MaxValue` is the equivalent of 23:59:59.9999999 UTC which is a one 100-nanosecond (a tenth of a microsecond) before 00:00:00 UTC, January 1, 10000. When that is parsed by `isodate.parse_datetime` it raises the exception described above - it parses 59.9999999 (7 nines) as 60. Instead I think it should cap at 1 microsecond away from 60 as it seems that is the smallest unit of time `datetime.time` can express and the full minute is not meant.

**Comment by gweis** [comment]
fixed in 89f8089
